name: spotify_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  email_validator:
  equatable:
  get_it: ^8.0.0
  dartz: ^0.10.1
  just_audio: ^0.9.40
  flutter_svg: ^2.0.10+1
  retrofit: ^4.4.1
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  spotify: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
