name: spotify_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  email_validator:
  equatable:
  get_it: ^8.0.0
  dartz: ^0.10.1
  just_audio: ^0.9.40
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.10+1
  retrofit:
  dio:
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  spotify: ^0.13.7
  modal_bottom_sheet: 
  youtube_explode_dart: 
  palette_generator:
  intl:
  audio_video_progress_bar:
  scrollable_positioned_list: ^0.3.8
  http:
  provider: ^6.1.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  google_nav_bar: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable:
  build_runner:
  retrofit_generator:
  analyzer:

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
